name: Hello World!

on:
  push:
    branches:
      - master
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - date: Run Date
        run: |
          date
      - ls: Run ls
        run: |
          ls
