name: Deploy pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    if: github.repository == 'harshal-99/full-stack-open-pokedex'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokemon-actions"
          heroku_email: "harshalpawshekar999@gmail.com"
          branch: "master"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test

